### ISSUE TITLE
 npm run create-local报错 HTTP error creating the subgraph: ECONNRESET，如何解决

### ISSUE THREAD

**Issue by shifangqi-github** [dukedaily/solidity-expert#10]
PS D:\test\worldcup> npm run create-local

> create-local
> graph create --node http://localhost:8020/ worldcup

 »   Warning: In next major version, this command will be merged as a subcommand for `graph local`.
× HTTP error creating the subgraph: ECONNRESET
D:\test\worldcup\node_modules\@oclif\core\lib\errors\index.js:21
    throw new exit_2.ExitError(code);
    ^

ExitError: EEXIT: 1
    at Object.exit (D:\test\worldcup\node_modules\@oclif\core\lib\errors\index.js:21:11)
    at CreateCommand.exit (D:\test\worldcup\node_modules\@oclif\core\lib\command.js:131:23)
    at D:\test\worldcup\node_modules\@graphprotocol\graph-cli\dist\commands\create.js:50:22
    at Client._parseResponse (D:\test\worldcup\node_modules\jayson\lib\client\index.js:190:12)
    at D:\test\worldcup\node_modules\jayson\lib\client\index.js:149:10
    at ClientRequest.<anonymous> (D:\test\worldcup\node_modules\jayson\lib\client\http.js:100:7)
    at ClientRequest.emit (node:events:517:28)
    at Socket.socketOnEnd (node:_http_client:525:9)
    at Socket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12) {
  oclif: { exit: 1 },
  code: 'EEXIT'
}

Node.js v18.20.2

**Comment by lujina** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我已收到邮件^^。

**Comment by shifangqi-github** [comment]
https://doc.pursue.pub/02.%E5%8C%BA%E5%9D%97%E9%93%BE/24.The%20Graph%E7%9A%84GraphNode%E5%92%8CSubgraph%E6%9C%AC%E5%9C%B0%E6%90%AD%E5%BB%BA.html
