### ISSUE TITLE
verify时报错，能帮我看看吗

### ISSUE THREAD

**Issue by LPC1616** [dukedaily/solidity-expert#7]
报错信息如下
```
ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (/home/sdf/worldcup-competition/node_modules/undici/lib/core/connect.js:176:24)
    at /home/sdf/worldcup-competition/node_modules/undici/lib/core/connect.js:123:46
    at Immediate._onImmediate (/home/sdf/worldcup-competition/node_modules/undici/lib/core/connect.js:164:9)
    at processImmediate (node:internal/timers:466:21) {
  code: 'UND_ERR_CONNECT_TIMEOUT'
}
```
clash已使用TUN模式

**Comment by dukedaily** [comment]
估计是梯子问题

**Comment by daocore** [comment]
如果是hardhat-etherscan验证的话，加入如下代码到hardhat.config.js中： 

```
// set proxy
const { ProxyAgent, setGlobalDispatcher } = require("undici");
const proxyAgent = new ProxyAgent('http://127.0.0.1:7890'); // 换成你自己的代理的端口即可，clash应该也是7890
setGlobalDispatcher(proxyAgent);
```
